config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("designs/", include("designs.urls", namespace="designs")),
    path("feet/", include("feet.urls", namespace="feet")),
    path("carts/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("chats/", include("chats.urls", namespace="chats")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from products import views as product_views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

designs/urls.py
from django.urls import path
from . import views

app_name = "designs"

urlpatterns = [
    path("customize/<int:pk>/", views.CustomizeView.as_view(), name="customize"),
    path("apply/", views.get_palette, name="apply"),
    path("gallery/", views.GalleriesListView.as_view(), name="galleries"),
    path(
        "gallery/category-<int:pk>/",
        views.GalleriesListByCategoryView.as_view(),
        name="galleries-category",
    ),
    path(
        "gallery/product-<int:pk>/",
        views.GalleriesListByProductView.as_view(),
        name="galleries-product",
    ),
    path("gallery/like/", views.design_like, name="like"),
]

designs/forms.py
import re
import base64
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models


class CustomizeForm(forms.ModelForm):
    class Meta:
        model = models.Design
        fields = (
            "outsole_color_left",
            "midsole_color_left",
            "uppersole_color_left",
            "shoelace_color_left",
            "tongue_color_left",
            "outsole_color_right",
            "midsole_color_right",
            "uppersole_color_right",
            "shoelace_color_right",
            "tongue_color_right",
            "outsole_material_left",
            "midsole_material_left",
            "uppersole_material_left",
            "shoelace_material_left",
            "tongue_material_left",
            "outsole_material_right",
            "midsole_material_right",
            "uppersole_material_right",
            "shoelace_material_right",
            "tongue_material_right",
            "image_data_front",
            "image_data_side",
            "image_data_up",
            "image_data_down",
        )
        widgets = {
            "outsole_color_left": forms.HiddenInput(),
            "midsole_color_left": forms.HiddenInput(),
            "uppersole_color_left": forms.HiddenInput(),
            "shoelace_color_left": forms.HiddenInput(),
            "tongue_color_left": forms.HiddenInput(),
            "liner_color_left": forms.HiddenInput(),
            "outsole_color_right": forms.HiddenInput(),
            "midsole_color_right": forms.HiddenInput(),
            "uppersole_color_right": forms.HiddenInput(),
            "shoelace_color_right": forms.HiddenInput(),
            "tongue_color_right": forms.HiddenInput(),
            "liner_color_right": forms.HiddenInput(),
            "outsole_material_left": forms.HiddenInput(),
            "midsole_material_left": forms.HiddenInput(),
            "uppersole_material_left": forms.HiddenInput(),
            "shoelace_material_left": forms.HiddenInput(),
            "tongue_material_left": forms.HiddenInput(),
            "liner_material_left": forms.HiddenInput(),
            "outsole_material_right": forms.HiddenInput(),
            "midsole_material_right": forms.HiddenInput(),
            "uppersole_material_right": forms.HiddenInput(),
            "shoelace_material_right": forms.HiddenInput(),
            "tongue_material_right": forms.HiddenInput(),
            "liner_material_right": forms.HiddenInput(),
        }

    image_data_front = forms.CharField(widget=forms.HiddenInput(), required=False)
    image_data_side = forms.CharField(widget=forms.HiddenInput(), required=False)
    image_data_up = forms.CharField(widget=forms.HiddenInput(), required=False)
    image_data_down = forms.CharField(widget=forms.HiddenInput(), required=False)

designs/views.py
import base64, json
from django.core.files.base import ContentFile
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import View, ListView
from designs import models as design_models
from products import models as product_models
from users import models as user_models
from . import models, forms


# インコードした画像データを画像にデコードする関数
def base64_file(data, name=None):
    _format, _img_str = data.split(";base64,")
    _name, ext = _format.split("/")
    if not name:
        name = _name.split(":")[-1]
    return ContentFile(base64.b64decode(_img_str), name="{}.{}".format(name, ext))


class CustomizeView(ListView):

    """ デザインカスタマイズ """

    model = models.Design
    template_name = "designs/design-customize.html"
    context_object_name = "designs"
    paginate_by = 5

    def get_template_names(self):
        if self.request.is_ajax():
            return ["mixins/designs/related_design_card.html"]
        return super(CustomizeView, self).get_template_names()

    def get_queryset(self):
        pk = self.kwargs.get("pk")
        designs = (
            models.Design.objects.filter(product=pk).exclude(user__isnull=True).all()
        )
        return sorted(designs, key=lambda design: design.total_likes, reverse=True)

    def get_context_data(self, *args, **kwargs):
        pk = self.kwargs.get("pk")
        materials = design_models.Material.objects.all().order_by("created")
        context = super(CustomizeView, self).get_context_data(*args, **kwargs)
        for material in materials:
            context["mat" + str(material.pk)] = material
        context["product"] = product_models.Product.objects.get(pk=pk)
        context["template"] = product_models.Template.objects.get(product=pk)
        context["form"] = forms.CustomizeForm()
        return context

    def post(self, *args, **kwargs):
        pk = self.kwargs.get("pk")
        customize_form = forms.CustomizeForm(self.request.POST)
        if self.request.user.is_authenticated:
            user = self.request.user
        else:
            user = None
        customize_data = {
            "outsole_color_left": self.request.POST.get("outsole_color_left"),
            "midsole_color_left": self.request.POST.get("midsole_color_left"),
            "uppersole_color_left": self.request.POST.get("uppersole_color_left"),
            "shoelace_color_left": self.request.POST.get("shoelace_color_left"),
            "tongue_color_left": self.request.POST.get("tongue_color_left"),
            "outsole_color_right": self.request.POST.get("outsole_color_right"),
            "midsole_color_right": self.request.POST.get("midsole_color_right"),
            "uppersole_color_right": self.request.POST.get("uppersole_color_right"),
            "shoelace_color_right": self.request.POST.get("shoelace_color_right"),
            "tongue_color_right": self.request.POST.get("tongue_color_right"),
            "outsole_material_left": self.request.POST.get("outsole_material_left"),
            "midsole_material_left": self.request.POST.get("midsole_material_left"),
            "uppersole_material_left": self.request.POST.get("uppersole_material_left"),
            "shoelace_material_left": self.request.POST.get("shoelace_material_left"),
            "tongue_material_left": self.request.POST.get("tongue_material_left"),
            "outsole_material_right": self.request.POST.get("outsole_material_right"),
            "midsole_material_right": self.request.POST.get("midsole_material_right"),
            "uppersole_material_right": self.request.POST.get(
                "uppersole_material_right"
            ),
            "shoelace_material_right": self.request.POST.get("shoelace_material_right"),
            "tongue_material_right": self.request.POST.get("tongue_material_right"),
        }
        new_design = design_models.Design.objects.create(
            user=user,
            product=product_models.Product.objects.get(pk=pk),
            outsole_color_left=customize_data["outsole_color_left"],
            midsole_color_left=customize_data["midsole_color_left"],
            uppersole_color_left=customize_data["uppersole_color_left"],
            shoelace_color_left=customize_data["shoelace_color_left"],
            tongue_color_left=customize_data["tongue_color_left"],
            outsole_color_right=customize_data["outsole_color_right"],
            midsole_color_right=customize_data["midsole_color_right"],
            uppersole_color_right=customize_data["uppersole_color_right"],
            shoelace_color_right=customize_data["shoelace_color_right"],
            tongue_color_right=customize_data["tongue_color_right"],
            outsole_material_left=models.Material.objects.get(
                pk=customize_data["outsole_material_left"]
            ),
            midsole_material_left=models.Material.objects.get(
                pk=customize_data["midsole_material_left"]
            ),
            uppersole_material_left=models.Material.objects.get(
                pk=customize_data["uppersole_material_left"]
            ),
            shoelace_material_left=models.Material.objects.get(
                pk=customize_data["shoelace_material_left"]
            ),
            tongue_material_left=models.Material.objects.get(
                pk=customize_data["tongue_material_left"]
            ),
            outsole_material_right=models.Material.objects.get(
                pk=customize_data["outsole_material_right"]
            ),
            midsole_material_right=models.Material.objects.get(
                pk=customize_data["midsole_material_right"]
            ),
            uppersole_material_right=models.Material.objects.get(
                pk=customize_data["uppersole_material_right"]
            ),
            shoelace_material_right=models.Material.objects.get(
                pk=customize_data["shoelace_material_right"]
            ),
            tongue_material_right=models.Material.objects.get(
                pk=customize_data["tongue_material_right"]
            ),
        )

        # 画像情報をデータベースに反映する
        image_data_front = self.request.POST.get("image_data_front")
        image_data_side = self.request.POST.get("image_data_side")
        image_data_up = self.request.POST.get("image_data_up")
        image_data_down = self.request.POST.get("image_data_down")
        design_models.Image.objects.create(
            design=new_design,
            front=base64_file(image_data_front),
            side=base64_file(image_data_side),
            up=base64_file(image_data_up),
            down=base64_file(image_data_down),
        )
        self.request.session["product"] = pk
        self.request.session["design"] = new_design.pk
        return redirect("feet:check")


def get_palette(request):

    """ 参照用デザインパレットを呼び出すビュー """

    if request.method == "POST" and request.is_ajax():
        outsole_color_left = request.POST.get("outsole_color_left")
        midsole_color_left = request.POST.get("midsole_color_left")
        uppersole_color_left = request.POST.get("uppersole_color_left")
        shoelace_color_left = request.POST.get("shoelace_color_left")
        tongue_color_left = request.POST.get("tongue_color_left")
        outsole_color_right = request.POST.get("outsole_color_right")
        midsole_color_right = request.POST.get("midsole_color_right")
        uppersole_color_right = request.POST.get("uppersole_color_right")
        shoelace_color_right = request.POST.get("shoelace_color_right")
        tongue_color_right = request.POST.get("tongue_color_right")
        name_outsole_material_left = models.Material.objects.get(
            pk=request.POST.get("outsole_material_left")
        ).name
        name_midsole_material_left = models.Material.objects.get(
            pk=request.POST.get("midsole_material_left")
        ).name
        name_uppersole_material_left = models.Material.objects.get(
            pk=request.POST.get("uppersole_material_left")
        ).name
        name_shoelace_material_left = models.Material.objects.get(
            pk=request.POST.get("shoelace_material_left")
        ).name
        name_tongue_material_left = models.Material.objects.get(
            pk=request.POST.get("tongue_material_left")
        ).name
        name_outsole_material_right = models.Material.objects.get(
            pk=request.POST.get("outsole_material_right")
        ).name
        name_midsole_material_right = models.Material.objects.get(
            pk=request.POST.get("midsole_material_right")
        ).name
        name_uppersole_material_right = models.Material.objects.get(
            pk=request.POST.get("uppersole_material_right")
        ).name
        name_shoelace_material_right = models.Material.objects.get(
            pk=request.POST.get("shoelace_material_right")
        ).name
        name_tongue_material_right = models.Material.objects.get(
            pk=request.POST.get("tongue_material_right")
        ).name
        outsole_material_left = models.Material.objects.get(
            pk=request.POST.get("outsole_material_left")
        ).file.url
        midsole_material_left = models.Material.objects.get(
            pk=request.POST.get("midsole_material_left")
        ).file.url
        uppersole_material_left = models.Material.objects.get(
            pk=request.POST.get("uppersole_material_left")
        ).file.url
        shoelace_material_left = models.Material.objects.get(
            pk=request.POST.get("shoelace_material_left")
        ).file.url
        tongue_material_left = models.Material.objects.get(
            pk=request.POST.get("tongue_material_left")
        ).file.url
        outsole_material_right = models.Material.objects.get(
            pk=request.POST.get("outsole_material_right")
        ).file.url
        midsole_material_right = models.Material.objects.get(
            pk=request.POST.get("midsole_material_right")

templates/mixins/designs/design-card.html
{% load i18n %}
<div class="w-full mb-10 overflow-hidden shadow-md wow fadeIn">
    <div class="w-full flex items-center justify-between bg-gray-600 h-12 text-white px-5">
        <h3 class="font-semibold text-lg">{{ design.customize_code }}</h3>
        <span class="">{% trans '作成日' %}：{{ design.created|date:'Y-m-d' }}</span>
    </div>
    {% with design.images.all|first as image %}
    <div class="flex flex-no-wrap py-10 px-5">
        <div style="background-image: url({{ image.front.url }});" class="w-1/4 h-40 bg-cover bg-center mr-3">
        </div>
        <div style="background-image: url({{ image.side.url }});" class="w-1/4 h-40 bg-cover bg-center mr-3">
        </div>
        <div style="background-image: url({{ image.up.url }});" class="w-1/4 h-40 bg-cover bg-center mr-3">
        </div>
        <div style="background-image: url({{ image.down.url }});" class="w-1/4 h-40 bg-cover bg-center">
        </div>
    </div>
    {% endwith %}
    <div class="w-full flex justify-around mb-5">
        <form method="POST" class="w-1/3">
            {% csrf_token %}
            <input type="hidden" name="target-design-modify" value="{{ design.id }}">
            <button name="design_modify" class="btn-warning text-white p-3">{% trans '変更する' %}</button>
        </form>
        <form method="POST" class="w-1/3">
            {% csrf_token %}
            <input type="hidden" name="target-design-delete" value="{{ design.id }}">
            <button name="design_delete" class="btn-danger text-white p-3">{% trans '削除する' %}</a>
        </form>
    </div>
</div>

templates/mixins/designs/related_design_card.html
{% load i18n static js %}
{% if designs %}
{% for design in designs %}
<a id="design_{{ design.pk }}" class="block min-w-1/5 border border-gray-200 p-3 cursor-pointer">
    <form id="form_{{ design.pk }}" action="{% url 'designs:apply' %}" method="POST" class="design-form w-full h-full">
        {% csrf_token %}
        <div class="w-full h-2/3 bg-cover bg-center mb-2" style="background-image: url({{ design.first_image }});">
        </div>
        <div class="flex justify-between items-center">
            <span class="text-black block font-medium">{{ design.customize_code }}</span>
            <span><i class="fas fa-heart text-sm"></i> {{ design.total_likes }}</span>
        </div>
        <div class="overflow-hidden text-left">
            <span class="text-sm text-black block font-medium">作成者：{{ design.user.get_email_name }}</span>
        </div>
        <input type="hidden" name="outsole_color_left" id="{{ design.pk }}_outsole_color_left"
            value="{{ design.outsole_color_left }}">
        <input type="hidden" name="midsole_color_left" id="{{ design.pk }}_midsole_color_left"
            value="{{ design.midsole_color_left }}">
        <input type="hidden" name="uppersole_color_left" id="{{ design.pk }}_uppersole_color_left"
            value="{{ design.uppersole_color_left }}">
        <input type="hidden" name="shoelace_color_left" id="{{ design.pk }}_shoelace_color_left"
            value="{{ design.shoelace_color_left }}">
        <input type="hidden" name="tongue_color_left" id="{{ design.pk }}_tongue_color_left"
            value="{{ design.tongue_color_left }}">
        <input type="hidden" name="liner_color_left" id="{{ design.pk }}_liner_color_left"
            value="{{ design.liner_color_left }}">
        <input type="hidden" name="outsole_color_right" id="{{ design.pk }}_outsole_color_right"
            value="{{ design.outsole_color_right }}">
        <input type="hidden" name="midsole_color_right" id="{{ design.pk }}_midsole_color_right"
            value="{{ design.midsole_color_right }}">
        <input type="hidden" name="uppersole_color_right" id="{{ design.pk }}_uppersole_color_right"
            value="{{ design.uppersole_color_right }}">
        <input type="hidden" name="shoelace_color_right" id="{{ design.pk }}_shoelace_color_right"
            value="{{ design.shoelace_color_right }}">
        <input type="hidden" name="tongue_color_right" id="{{ design.pk }}_tongue_color_right"
            value="{{ design.tongue_color_right }}">
        <input type="hidden" name="liner_color_right" id="{{ design.pk }}_liner_color_right"
            value="{{ design.liner_color_right }}">

        <input type="hidden" name="outsole_material_left" id="{{ design.pk }}_outsole_material_left"
            value="{{ design.outsole_material_left.pk }}">
        <input type="hidden" name="midsole_material_left" id="{{ design.pk }}_midsole_material_left"
            value="{{ design.midsole_material_left.pk }}">
        <input type="hidden" name="uppersole_material_left" id="{{ design.pk }}_uppersole_material_left"
            value="{{ design.uppersole_material_left.pk }}">
        <input type="hidden" name="shoelace_material_left" id="{{ design.pk }}_shoelace_material_left"
            value="{{ design.shoelace_material_left.pk }}">
        <input type="hidden" name="tongue_material_left" id="{{ design.pk }}_tongue_material_left"
            value="{{ design.tongue_material_left.pk }}">
        <input type="hidden" name="outsole_material_right" id="{{ design.pk }}_outsole_material_right"
            value="{{ design.outsole_material_right.pk }}">
        <input type="hidden" name="midsole_material_right" id="{{ design.pk }}_midsole_material_right"
            value="{{ design.midsole_material_right.pk }}">
        <input type="hidden" name="uppersole_material_right" id="{{ design.pk }}_uppersole_material_right"
            value="{{ design.uppersole_material_right.pk }}">
        <input type="hidden" name="shoelace_material_right" id="{{ design.pk }}_shoelace_material_right"
            value="{{ design.shoelace_material_right.pk }}">
        <input type="hidden" name="tongue_material_right" id="{{ design.pk }}_tongue_material_right"
            value="{{ design.tongue_material_right.pk }}">
    </form>
</a>
{% endfor %}
{% else %}
<p class="flex justify-center items-center font-semibold w-full text-center text-2xl">
    <i class="fas fa-dizzy fa-2x text-purple-500"></i> <span class="ml-5">{% trans 'デザインパレットが存在しません。' %}</span>
</p>
{% endif %}

templates/mixins/designs/select-product-card.html
<div class="xl:w-1/3 md:w-1/2 sm:w-full xs:w-full overflow-hidden border border-gray-300 bg-white p-5 wow fadeIn"
    style="height: 22.5vw;">
    <a href="{% url 'users:customize' product.pk %}">
        <div class="w-full h-2/3 bg-cover bg-center mb-2" style="background-image: url({{ product.first_image }});">
        </div>
        <div class="flex flex-col h-1/3 justify-center">
            <div class="flex justify-between items-end mb-2 truncate">
                <div class="w-4/5 overflow-hidden flex">
                    <span class="text-lg text-black w-11/12 block overflow-hidden font-medium">{{ product.name }}</span>
                </div>
                <span class="text-blue-600 font-medium">
                    <span class="text-sm text-gray-600 block truncate"> {{ product.category }}</span>
                </span>
            </div>
        </div>
    </a>
</div>