carts/urls.py
from django.urls import path
from . import views

app_name = "carts"

urlpatterns = [
    path("", views.cart_display, name="cart"),
    path("add/<int:pk>/<int:design_pk>/", views.add_cart, name="add_cart"),
    path("remove/<int:pk>/<int:design_pk>/", views.remove_item, name="remove",),
    path(
        "delete-item/<int:pk>/<int:design_pk>/", views.delete_cartitem, name="delete",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("designs/", include("designs.urls", namespace="designs")),
    path("feet/", include("feet.urls", namespace="feet")),
    path("carts/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("chats/", include("chats.urls", namespace="chats")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from products import views as product_views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("member_or_guest/", views.member_or_guest_login, name="member_or_guest"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("checkout/payment/", views.SelectPaymentView.as_view(), name="select-payment"),
    path("checkout/check/", views.OrderCheckView.as_view(), name="order-check"),
    path(
        "checkout/done/<str:order_code>",
        views.CheckoutDoneView.as_view(),
        name="checkout-done",
    ),
    path("search/", views.OrderSearchView.as_view(), name="search"),
    path("detail/<str:order_code>/", views.OrderDetailView.as_view(), name="detail"),
    path("receipt/<str:order_code>/", views.ReceiptView.as_view(), name="receipt"),
    path("bill/<str:order_code>/", views.BillView.as_view(), name="bill"),
]

carts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from core import models as core_models
from users import models as user_models


class CartItem(models.Model):

    """ カート内のアイテムのモデルを定義する """

    cart = models.ForeignKey(
        "Cart",
        related_name="cart_items",
        verbose_name=_("カート"),
        on_delete=models.CASCADE,
    )
    design = models.ForeignKey(
        "designs.Design",
        verbose_name=_("デザイン"),
        related_name="cart_items",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    product = models.ForeignKey(
        "products.Product", verbose_name=_("商品"), on_delete=models.CASCADE
    )
    length_left = models.DecimalField(_("足長(左)"), max_digits=4, decimal_places=1)
    length_right = models.DecimalField(_("足長(右)"), max_digits=4, decimal_places=1)
    width_left = models.DecimalField(_("足幅(左)"), max_digits=4, decimal_places=1)
    width_right = models.DecimalField(_("足幅(右)"), max_digits=4, decimal_places=1)
    quantity = models.IntegerField(_("数量"), default=1)
    active = models.BooleanField(_("活性化"), default=True)

    def sub_total(self):
        return self.product.price * self.quantity


class Cart(core_models.TimeStampedModel):

    """ カートのモデルを定義する """

    user = models.ForeignKey(
        "users.User", null=True, verbose_name=_("会員"), on_delete=models.CASCADE
    )
    session_key = models.CharField(_("カートセッションキー"), max_length=254)

carts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from designs import models as design_models
from feet import models as foot_models
from products import models as product_models
from .models import Cart, CartItem


# 現在のセッション宛にカートを生成するための関数
def _session_key(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, pk, design_pk):

    """ カートに商品を追加するビュー """

    product = product_models.Product.objects.get(pk=pk)
    # カートを持っているかチェック
    try:
        cart = Cart.objects.get(session_key=_session_key(request))
    # 持っていない場合、カートを生成する
    except Cart.DoesNotExist:
        if request.user.is_authenticated:
            cart = Cart.objects.create(
                session_key=_session_key(request), user_id=request.user.pk
            )
            cart.save()
        else:
            cart = Cart.objects.create(session_key=_session_key(request))
            cart.save()
    # カート内に同じ商品かつ同じデザインのアイテムがあるかチェック
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart, design=design_pk)
        # 取得したアイテムのサイズとセッションのサイズ値が違う場合、ブラウザの前ボタンでサイズを修正したことのため、サイズのみをアップデートする
        if (
            cart_item.length_left != request.session["length_left"]
            or cart_item.length_right != request.session["length_right"]
            or cart_item.width_left != request.session["width_left"]
            or cart_item.width_right != request.session["width_right"]
        ):
            cart_item.length_left = request.session["length_left"]
            cart_item.length_right = request.session["length_right"]
            cart_item.width_left = request.session["width_left"]
            cart_item.width_right = request.session["width_right"]
        # サイズも同じな場合は全く同じ商品の追加になるため、数量を増やす
        else:
            cart_item.quantity += 1
        cart_item.save()
    # ない場合、新しくカートアイテムを生成する
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            design=design_models.Design.objects.get(pk=design_pk),
            length_left=request.session["length_left"],
            length_right=request.session["length_right"],
            width_left=request.session["width_left"],
            width_right=request.session["width_right"],
            quantity=1,
            cart=cart,
        )
        cart_item.save()
    return redirect("carts:cart")


def cart_display(request, amount=0, counter=0, cart_items=None):

    """ カートの内容を表示するためのビュー """

    # セッションキーに対しカートが既に存在する場合
    try:
        cart = Cart.objects.get(session_key=_session_key(request))
        cart_items = CartItem.objects.filter(cart=cart)
        for cart_item in cart_items:
            amount += cart_item.product.price * cart_item.quantity
            counter += cart_item.quantity
    # カートが存在しない場合
    except ObjectDoesNotExist:
        pass
    return render(
        request,
        "carts/cart.html",
        {"cart_items": cart_items, "amount": amount, "counter": counter},
    )


def remove_item(request, pk, design_pk):

    """ カートに入れた商品の個数を減少させるためのビュー """

    # データベースから関連項目を取得する
    cart = Cart.objects.get(session_key=_session_key(request))
    product = get_object_or_404(product_models.Product, pk=pk)
    cart_item = CartItem.objects.get(product=product, cart=cart, design=design_pk)
    # 削除しようとするカートアイテムの数が1より多い場合
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    # 削除しようとするカートアイテムの数が1以下の場合
    else:
        cart_item.delete()
    return redirect("carts:cart")


def delete_cartitem(request, pk, design_pk):

    """ 商品項目をカートから削除するためのビュー """

    # データベースから関連項目を取得し、対象カートアイテムを削除する
    cart = Cart.objects.get(session_key=_session_key(request))
    product = get_object_or_404(product_models.Product, pk=pk)
    cart_item = CartItem.objects.get(product=product, cart=cart, design=design_pk)
    cart_item.delete()
    return redirect("carts:cart")

templates/carts/cart.html
{% extends "base.html" %}
{% load i18n static humanize %}

{% block page_title %}
{% trans 'カート' %}
{% endblock page_title %}

{% block content %}
<div class="flex min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-4/5 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-shopping-bag fa-3x text-white wow fadeIn"></i>
        </div>
        <div class="w-full flex items-start justify-between">
            <div class="w-2/3 bg-white mr-16">
                <h3 class="w-full font-black text-2xl text-left p-5 text-indigo-800">
                    {% trans 'ショッピングカート' %}
                </h3>
                <div class="flex flex-col">
                    {% if cart_items %}
                    {% for cart_item in cart_items %}
                    <div class="w-full flex flex-no-wrap shadow-md rounded-lg m-5 p-5 h-auto wow fadeIn">
                        {% with cart_item.design.images.all|first as image %}
                        <div class="w-1/3 h-auto bg-center bg-cover"
                            style="background-image: url('{{ image.front.url }}');">
                        </div>
                        {% endwith %}
                        <div class="w-full flex px-5 items-center">
                            <div class="w-full flex flex-col justify-between h-full">
                                <div class="flex justify-between items-center">
                                    <span class="text-lg">{{ cart_item.product.name }}</span>
                                    <div class="text-indigo-600">
                                        &yen; {{ cart_item.sub_total | intcomma }}
                                    </div>
                                </div>
                                <div class="flex flex-col">
                                    <span class="text-gray-500 text-xs">{{ cart_item.product.category }}</span>
                                    <span class="text-gray-500 text-xs">{% trans '左足' %}
                                        {{ cart_item.length_left }}mm {% trans '(足長)' %}
                                        {{ cart_item.width_left }}mm {% trans '(足幅)' %}</span>
                                    <span class="text-gray-500 text-xs">{% trans '右足' %}
                                        {{ cart_item.length_right }}mm {% trans '(足長)' %}
                                        {{ cart_item.width_right }}mm {% trans '(足幅)' %}</span>
                                </div>
                                <div class="flex justify-between items-center mt-3">
                                    <span class="text-sm">{% trans '単価' %}　&yen;
                                        {{ cart_item.product.price | intcomma }}</span>
                                    <div class="text-xs ml-5">
                                        <a href="{% url 'carts:add_cart' cart_item.product.pk cart_item.design.pk %}">
                                            <i class="fas fa-plus-circle fa-lg text-indigo-600"></i>
                                        </a>
                                        <span class="mx-2 text-sm">{{ cart_item.quantity }}</span>
                                        <a href="{% url 'carts:remove' cart_item.product.pk cart_item.design.pk %}">
                                            <i class="fas fa-minus-circle fa-lg text-indigo-600"></i>
                                        </a>
                                    </div>
                                    <div class="text-sm">
                                        <a href="{% url 'carts:delete' cart_item.product.pk cart_item.design.pk %}"
                                            class="bg-red-500 py-1 px-5 rounded">
                                            <span><i class="fas fa-trash-alt text-white"></i></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p
                        class="flex justify-center items-center font-semibold w-full h-50vh text-center text-2xl wow fadeIn">
                        <i class="fas fa-dizzy fa-2x text-indigo-600"></i> <span
                            class="ml-5">{% trans 'カートに商品が入っていません。' %}</span>
                    </p>
                    {% endif %}
                </div>
            </div>
            <div
                class="w-1/3 flex flex-col shadow-lg items-center justify-between bg-gray-900 shadow-lg relative mt-5 rounded-xl wow fadeIn">
                <h3 class="text-white font-semibold w-full p-3 mt-3 text-2xl text-center">
                    {% trans 'ご注文金額' %}
                </h3>
                <div class="w-full p-5 text-white">
                    <div class="flex flex-no-wrap justify-between">
                        <div>{% trans '合計（税込）' %}</div>
                        <div class="font-semibold">&yen; {{ amount | intcomma }}</div>
                    </div>
                    {% if cart_items %}
                    <a href=" {% url 'orders:member_or_guest' %}" class="btn block mt-10">{% trans '購入手続きへ' %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}