config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("designs/", include("designs.urls", namespace="designs")),
    path("feet/", include("feet.urls", namespace="feet")),
    path("carts/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("chats/", include("chats.urls", namespace="chats")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from products import views as product_views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("member_or_guest/", views.member_or_guest_login, name="member_or_guest"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("checkout/payment/", views.SelectPaymentView.as_view(), name="select-payment"),
    path("checkout/check/", views.OrderCheckView.as_view(), name="order-check"),
    path(
        "checkout/done/<str:order_code>",
        views.CheckoutDoneView.as_view(),
        name="checkout-done",
    ),
    path("search/", views.OrderSearchView.as_view(), name="search"),
    path("detail/<str:order_code>/", views.OrderDetailView.as_view(), name="detail"),
    path("receipt/<str:order_code>/", views.ReceiptView.as_view(), name="receipt"),
    path("bill/<str:order_code>/", views.BillView.as_view(), name="bill"),
]

orders/models.py
import random, string
from datetime import datetime, date
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from core import models as core_models
from core.models import JPPrefectureField


def create_order_number():
    last_order = Order.objects.all().order_by("pk").last()
    if not last_order:
        return "0001"
    order_number = last_order.order_number
    order_int = int(order_number)
    no_width = 4
    new_order_int = order_int + 1
    if not new_order_int == 10000:
        formatted = (no_width - len(str(new_order_int))) * "0" + str(new_order_int)
    else:
        formatted = "0001"
    new_order_number = str(formatted)
    return new_order_number


class Step(models.Model):

    """ 注文の対応状況に関するモデルを定義する """

    step_code = models.CharField(_("対応コード"), max_length=3)
    step_name = models.CharField(_("対応名"), max_length=20)

    def __str__(self):
        return self.step_name

    class Meta:
        ordering = ("step_code",)
        verbose_name = _("対応")
        verbose_name_plural = _("対応")


class Order(models.Model):

    """ 注文のモデルを定義する """

    PAYMENT_CARD = "P1"
    PAYMENT_TRANSFER = "P2"

    PAYMENT_CHOICES = ((PAYMENT_CARD, _("クレジットカード")), (PAYMENT_TRANSFER, _("振込")))

    user = models.ForeignKey(
        "users.User",
        related_name="order",
        verbose_name=_("ユーザー"),
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    guest = models.ForeignKey(
        "users.Guest",
        related_name="order",
        verbose_name=_("ゲスト"),
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    last_name_recipient = models.CharField(_("姓(ご請求書先)"), max_length=30)
    first_name_recipient = models.CharField(_("名(ご請求書先)"), max_length=30)
    last_name_recipient_kana = models.CharField(
        _("姓(ご請求書先,カナ)"),
        max_length=30,
        validators=[
            RegexValidator(
                regex="[ア-ンー]", message=_("全角カタカナで入力してください。"), code="invalid",
            ),
        ],
    )
    first_name_recipient_kana = models.CharField(
        _("名(ご請求書先,カナ)"),
        max_length=30,
        validators=[
            RegexValidator(
                regex="[ア-ンー]", message=_("全角カタカナで入力してください。"), code="invalid",
            ),
        ],
    )
    phone_number_recipient = PhoneNumberField(_("電話番号(ご請求書先)"), max_length=15)
    postal_code_recipient = models.CharField(_("郵便番号(ご請求書先)"), max_length=7)
    prefecture_recipient = JPPrefectureField(_("都道府県(ご請求書先)"), max_length=2)
    address_city_recipient = models.CharField(_("市区町村(ご請求書先)"), max_length=40)
    address_detail_recipient = models.CharField(_("建物名・部屋番号(ご請求書先)"), max_length=40)
    last_name_orderer = models.CharField(_("姓(お届け先)"), max_length=30)
    first_name_orderer = models.CharField(
        _("名(お届け先)"), max_length=30, null=True, blank=True
    )
    last_name_orderer_kana = models.CharField(
        _("姓(カナ, お届け先)"),
        max_length=30,
        null=True,
        blank=True,
        validators=[
            RegexValidator(
                regex="[ア-ンー]", message=_("全角カタカナで入力してください。"), code="invalid",
            ),
        ],
    )
    first_name_orderer_kana = models.CharField(
        _("名(カナ, お届け先)"),
        max_length=30,
        null=True,
        blank=True,
        validators=[
            RegexValidator(
                regex="[ア-ンー]", message=_("全角カタカナで入力してください。"), code="invalid",
            ),
        ],
    )
    phone_number_orderer = PhoneNumberField(
        _("電話番号(お届け先)"), max_length=15, null=True, blank=True
    )
    postal_code_orderer = models.CharField(
        _("郵便番号(お届け先)"), max_length=7, null=True, blank=True
    )
    prefecture_orderer = JPPrefectureField(
        _("都道府県(お届け先)"), max_length=2, null=True, blank=True
    )
    address_city_orderer = models.CharField(
        _("市区町村(お届け先)"), max_length=40, null=True, blank=True
    )
    address_detail_orderer = models.CharField(
        _("建物名・部屋番号(お届け先)"), max_length=40, null=True, blank=True
    )
    order_date = models.DateTimeField(_("注文日時"), auto_now_add=True)
    payment = models.CharField(_("支払方法"), max_length=2, choices=PAYMENT_CHOICES)
    stripe_charge_id = models.CharField(max_length=50, blank=True, null=True)
    step = models.ForeignKey(
        "Step",
        related_name="order",
        verbose_name=_("対応状況"),
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    amount = models.DecimalField(_("支払総額"), decimal_places=0, max_digits=10)
    order_number = models.CharField(
        max_length=40, default=create_order_number, blank=True, null=True
    )
    order_code = models.CharField(_("注文番号"), max_length=40, blank=True, null=True)

    class Meta:
        ordering = ("-order_date",)
        verbose_name = _("注文")
        verbose_name_plural = _("注文")

    def show_first_one(self):
        try:
            (order_item,) = self.order_items.all()[:1]
            return order_item.product
        except ValueError:
            return None

    def count_items_all(self):
        count = 0
        for order_item in self.order_items.all():
            count += order_item.quantity
        return count

    def count_items_except_one(self):
        return self.order_items.all().count() - 1


# モデルにデータを保存した後に注文コードを付与し再保存する
@receiver(post_save, sender=Order)
def set_order_code(sender, instance, created, **kwargs):
    if created:
        order_date = instance.order_date
        try:
            date_string = order_date.strftime("%y%m")
        except:
            temp = order_date.split("-")
            date_string = temp[0] + temp[1]
        if instance.user:
            instance.order_code = (
                date_string + instance.user.member_code + instance.order_number
            )
            instance.save()
        else:
            string_pool = string.ascii_uppercase
            char1 = random.choice(string_pool)
            char2 = random.choice(string_pool)
            instance.order_code = (
                date_string + "UWGUEST" + char1 + char2 + instance.order_number
            )
            instance.save()


class OrderItem(models.Model):
    order = models.ForeignKey(
        "Order",
        verbose_name=_("注文アイテム"),
        related_name="order_items",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        "products.Product",
        verbose_name=_("商品"),
        related_name="order_items",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    quantity = models.IntegerField(_("数量"))
    price = models.DecimalField(_("単価"), decimal_places=0, max_digits=6)
    front = models.ImageField(_("正面"), upload_to="orders")
    side = models.ImageField(_("側面"), upload_to="orders")
    up = models.ImageField(_("上面"), upload_to="orders")
    down = models.ImageField(_("下面"), upload_to="orders")
    outsole_color_left = models.CharField("アウトソール色(左)", max_length=7)
    outsole_material_left = models.CharField("アウトソール素材(左)", max_length=20)
    midsole_color_left = models.CharField("ミッドソール色(左)", max_length=7)
    midsole_material_left = models.CharField("ミッドソール素材(左)", max_length=20)
    uppersole_color_left = models.CharField("アッパーソール色(左)", max_length=7)
    uppersole_material_left = models.CharField("アッパーソール素材(左)", max_length=20)
    shoelace_color_left = models.CharField("シューレース色(左)", max_length=7)
    shoelace_material_left = models.CharField("シューレース素材(左)", max_length=20)
    tongue_color_left = models.CharField("タン色(左)", max_length=7)
    tongue_material_left = models.CharField("タン素材(左)", max_length=20)
    outsole_color_right = models.CharField("アウトソール色(右)", max_length=7)
    outsole_material_right = models.CharField("アウトソール素材(右)", max_length=20)
    midsole_color_right = models.CharField("ミッドソール色(右)", max_length=7)
    midsole_material_right = models.CharField("ミッドソール素材(右)", max_length=20)
    uppersole_color_right = models.CharField("アッパーソール色(右)", max_length=7)
    uppersole_material_right = models.CharField("アッパーソール素材(右)", max_length=20)
    shoelace_color_right = models.CharField("シューレース色(右)", max_length=7)
    shoelace_material_right = models.CharField("シューレース素材(右)", max_length=20)
    tongue_color_right = models.CharField("タン色(右)", max_length=7)
    tongue_material_right = models.CharField("タン素材(右)", max_length=20)
    customize_code = models.CharField(_("カスタマイズデザインコード"), max_length=11)
    length_left = models.DecimalField(_("足長(左)"), max_digits=3, decimal_places=0)
    length_right = models.DecimalField(_("足長(右)"), max_digits=3, decimal_places=0)
    width_left = models.DecimalField(_("足幅(左)"), max_digits=3, decimal_places=0)
    width_right = models.DecimalField(_("足幅(右)"), max_digits=3, decimal_places=0)

    def sub_total(self):
        return self.quantity * self.price

orders/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from localflavor.jp.forms import JPPostalCodeField
from phonenumber_field import formfields
from . import models


PAYMENT_CARD = "P1"
PAYMENT_TRANSFER = "P2"

PAYMENT_CHOICES = ((PAYMENT_CARD, _("クレジットカード")), (PAYMENT_TRANSFER, _("振込")))


class GuestForm(forms.Form):
    email = forms.EmailField(
        label="", widget=forms.EmailInput(attrs={"placeholder": _("メールアドレス")})
    )


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = (
            "last_name_recipient",
            "first_name_recipient",
            "last_name_recipient_kana",
            "first_name_recipient_kana",
            "phone_number_recipient",
            "postal_code_recipient",
            "prefecture_recipient",
            "address_city_recipient",
            "address_detail_recipient",
        )
        widgets = (
            {
                "last_name_recipient": forms.TextInput(attrs={"placeholder": _("姓")}),
                "first_name_recipient": forms.TextInput(attrs={"placeholder": _("名")}),
                "last_name_recipient_kana": forms.TextInput(
                    attrs={"placeholder": _("姓(カナ)")}
                ),
                "first_name_recipient_kana": forms.TextInput(
                    attrs={"placeholder": _("名(カナ)")}
                ),
                "phone_number_recipient": forms.TextInput(
                    attrs={"placeholder": _("電話番号")}
                ),
                "prefecture_recipient": forms.TextInput(
                    attrs={"placeholder": _("都道府県")}
                ),
                "address_city_recipient": forms.TextInput(
                    attrs={"placeholder": _("市区町村番地")}
                ),
                "address_detail_recipient": forms.TextInput(
                    attrs={"placeholder": _("建物名・号室")}
                ),
            },
        )

    last_name_recipient = forms.CharField(
        label=_("姓"), widget=forms.TextInput(attrs={"placeholder": _("姓")})
    )
    first_name_recipient = forms.CharField(
        label=_("名"), widget=forms.TextInput(attrs={"placeholder": _("名")})
    )
    last_name_recipient_kana = forms.CharField(
        label=_("姓(カナ)"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("姓(カナ)")}),
    )
    first_name_recipient_kana = forms.CharField(
        label=_("名(カナ)"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("名(カナ)")}),
    )
    phone_number_recipient = forms.CharField(
        label=_("電話番号"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("電話番号")}),
    )
    address_city_recipient = forms.CharField(
        label=_("市区町村番地"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("市区町村番地")}),
    )
    address_detail_recipient = forms.CharField(
        label=_("建物名・号室"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("建物名・号室")}),
    )
    postal_code_recipient = JPPostalCodeField(
        label=_("郵便番号"), 
        required=True, 
        widget=forms.TextInput(attrs={"placeholder": _("郵便番号")}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""


class SelectPaymentForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = (
            "payment",
            "last_name_orderer",
            "first_name_orderer",
            "last_name_orderer_kana",
            "first_name_orderer_kana",
            "phone_number_orderer",
            "postal_code_orderer",
            "prefecture_orderer",
            "address_city_orderer",
            "address_detail_orderer",
        )
        widgets = {
            "payment": forms.RadioSelect(),
            "last_name_orderer": forms.TextInput(attrs={"placeholder": _("姓")}),
            "first_name_orderer": forms.TextInput(attrs={"placeholder": _("名")}),
            "last_name_orderer_kana": forms.TextInput(
                attrs={"placeholder": _("姓(カナ)")}
            ),
            "first_name_orderer_kana": forms.TextInput(
                attrs={"placeholder": _("名(カナ)")}
            ),
            "phone_number_orderer": forms.TextInput(attrs={"placeholder": _("電話番号")}),
            "postal_code_orderer": forms.TextInput(attrs={"placeholder": _("郵便番号")}),
            "address_city_orderer": forms.TextInput(attrs={"placeholder": _("市区町村番地")}),
            "address_detail_orderer": forms.TextInput(
                attrs={"placeholder": _("建物名・号室")}
            ),
        }

    payment = forms.ChoiceField(choices=PAYMENT_CHOICES, widget=forms.RadioSelect())
    last_name_orderer = forms.CharField(
        label=_("姓"), widget=forms.TextInput(attrs={"placeholder": _("姓")})
    )
    first_name_orderer = forms.CharField(
        label=_("名"), widget=forms.TextInput(attrs={"placeholder": _("名")})
    )
    last_name_orderer_kana = forms.CharField(
        label=_("姓(カナ)"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("姓(カナ)")}),
    )
    first_name_orderer_kana = forms.CharField(
        label=_("名(カナ)"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("名(カナ)")}),
    )
    phone_number_orderer = forms.CharField(
        label=_("電話番号"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("電話番号")}),
    )
    address_city_orderer = forms.CharField(
        label=_("市区町村番地"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("市区町村番地")}),
    )
    address_detail_orderer = forms.CharField(
        label=_("建物名・号室"),
        required=True,
        widget=forms.TextInput(attrs={"placeholder": _("建物名・号室")}),
    )
    postal_code_orderer = JPPostalCodeField(
        label=_("郵便番号"), 
        required=True, 
        widget=forms.TextInput(attrs={"placeholder": _("郵便番号")}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""


class CardForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


class OrderSearchForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = (
            "order_code",
            "email",
        )

    order_code = forms.CharField(
        label=_("注文番号"),
        widget=forms.TextInput(attrs={"placeholder": _("注文番号"), "required": True}),
    )
    email = forms.EmailField(
        label=_("メールアドレス"),
        widget=forms.EmailInput(attrs={"placeholder": _("メールアドレス"), "required": True}),
    )

templates/orders/checkout.html
{% extends "base.html" %}
{% load i18n static humanize js %}

{% block page_title %}
{% trans 'ご購入の手続き' %}
{% endblock page_title %}

{% block content %}
<div class="min-h-75vh rounded-xl mx-auto py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="w-5/6 flex flex-col items-center container mx-auto bg-white p-12 my-10 rounded-xl relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-shopping-bag fa-3x text-white wow fadeIn"></i>
        </div>
        <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold text-center">
            {% trans 'ご購入の手続き' %}
        </h2>
        <div class="w-full flex">
            <div class="w-2/3 flex flex-wrap mb-10">
                <form method="POST" class="w-3/4 mx-auto">
                    <div id="orderer" class="py-5 wow fadeIn">
                        <h3 class="w-full font-semibold text-2xl bg-gray-900 p-3 text-white rounded-t-lg">
                            {% trans '1. お届け先情報' %}</h3>
                        <div class="border border-gray-500 rounded-b-lg px-4">
                            {% if request.user.is_authenticated %}
                            <a id="get_user_data"
                                class="block w-full btn-link mt-4 mb-8 cursor-pointer">{% trans '会員情報からデータを取得する' %}</a>
                            {% endif %}
                            {% csrf_token %}
                            <div class="flex my-5 ">
                                <div class="mr-5 border rounded px-3 pb-2">
                                    <div class="floating-label ">
                                        {{ recipient_form.last_name_recipient }}
                                        {{ recipient_form.last_name_recipient.label_tag }}
                                        <span
                                            class="text-red-700 font-medium text-xs">{{ recipient_form.last_name_recipient.errors }}</span>
                                    </div>
                                </div>
                                <div class="border rounded px-3 pb-2">
                                    <div class="floating-label">
                                        {{ recipient_form.first_name_recipient }}
                                        {{ recipient_form.first_name_recipient.label_tag }}
                                        <span
                                            class="text-red-700 font-medium text-xs">{{ recipient_form.first_name_recipient.errors }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="flex mb-5">
                                <div class="mr-5 border rounded px-3 pb-2">
                                    <div class="floating-label">
                                        {{ recipient_form.last_name_recipient_kana }}
                                        {{ recipient_form.last_name_recipient_kana.label_tag }}
                                        <span
                                            class="text-red-700 font-medium text-xs">{{ recipient_form.last_name_recipient_kana.errors }}</span>
                                    </div>
                                </div>
                                <div class="border rounded px-3 pb-2">
                                    <div class="floating-label">
                                        {{ recipient_form.first_name_recipient_kana }}
                                        {{ recipient_form.first_name_recipient_kana.label_tag }}
                                        <span
                                            class="text-red-700 font-medium text-xs">{{ recipient_form.first_name_recipient_kana.errors }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-5 border rounded px-3 py-1">
                                <div class="floating-label">
                                    {{ recipient_form.phone_number_recipient }}
                                    {{ recipient_form.phone_number_recipient.label_tag }}
                                    <span
                                        class="text-red-700 font-medium text-xs">{{ recipient_form.phone_number_recipient.errors }}</span>
                                </div>
                            </div>
                            <div class="mb-5 border rounded px-3 py-1">
                                <div class="floating-label">
                                    {{ recipient_form.postal_code_recipient }}
                                    {{ recipient_form.postal_code_recipient.label_tag }}
                                    <span
                                        class="text-red-700 font-medium text-xs ">{{ recipient_form.postal_code_recipient.errors }}</span>
                                </div>
                            </div>
                            <div class="floating-label select mb-5 border rounded px-3 py-2">
                                {{ recipient_form.prefecture_recipient }}
                                <span
                                    class="text-red-700 font-medium text-xs">{{ recipient_form.prefecture_recipient.errors }}</span>
                            </div>
                            <div class="mb-5 border rounded px-3 pb-2">
                                <div class="floating-label">
                                    {{ recipient_form.address_city_recipient }}
                                    {{ recipient_form.address_city_recipient.label_tag }}
                                    <span
                                        class="text-red-700 font-medium text-xs">{{ recipient_form.address_city_recipient.errors }}</span>
                                </div>
                            </div>
                            <div class="mb-5 border rounded px-3 pb-2">
                                <div class="floating-label">
                                    {{ recipient_form.address_detail_recipient }}
                                    {{ recipient_form.address_detail_recipient.label_tag }}
                                    <span
                                        class="text-red-700 font-medium text-xs">{{ recipient_form.address_detail_recipient.errors }}</span>
                                </div>
                            </div>
                            <button class="btn mb-4">{% trans 'お支払い方法の選択へ' %}</button>
                        </div>
                    </div>
                    <h3 class="w-full font-semibold text-xl mb-3 text-white bg-gray-900 p-3 rounded-lg">
                        {% trans '2. お支払い方法・ご請求先情報' %}</h3>
                    <h3 class="w-full font-semibold text-xl text-white bg-gray-900 p-3 rounded-lg">
                        {% trans '3. ご注文の確定' %}
                    </h3>
                </form>
            </div>
            <div
                class="w-1/3 flex flex-col h-full p-5 shadow-lg justify-between text-white bg-gray-900 rounded-xl my-5 mr-10">
                {% include "mixins/orders/order-summary-card.html" %}
            </div>
        </div>
    </div>
</div>

<script>
    //// 会員情報からデータを取得するための処理
    // DOMの取得
    const get_user_data_btn = document.querySelector("#get_user_data");
    const data = {{ recipient_info | js }};
    const first_name = document.querySelector("#id_first_name_recipient");
    const last_name = document.querySelector("#id_last_name_recipient");
    const first_name_kana = document.querySelector("#id_first_name_recipient_kana");
    const last_name_kana = document.querySelector("#id_last_name_recipient_kana");
    const phone_number = document.querySelector("#id_phone_number_recipient");
    const postal_code = document.querySelector("#id_postal_code_recipient");
    const prefecture = document.querySelector("#id_prefecture_recipient");
    const address_city = document.querySelector("#id_address_city_recipient");
    const address_detail = document.querySelector("#id_address_detail_recipient");

    // フォームに取得したデータを入れる
    get_user_data_btn.addEventListener("click", () => {
        first_name.value = data["first_name"];
        last_name.value = data["last_name"];
        first_name_kana.value = data["first_name_kana"];
        last_name_kana.value = data["last_name_kana"];
        phone_number.value = data["phone_number"];
        postal_code.value = data["postal_code"];
        prefecture.value = data["prefecture"];
        address_city.value = data["address_city"];
        address_detail.value = data["address_detail"];
    });
</script>
{% endblock content %}

templates/orders/search-order-detail.html
{% extends "base.html" %}
{% load i18n humanize static %}

{% block page_title %}
{% trans '注文詳細' %}
{% endblock page_title%}

{% block content %}
<div class="flex flex-col items-center min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-2/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-truck fa-3x text-white wow fadeIn"></i>
        </div>
        <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">
            {% trans '注文詳細' %}
        </h2>
        <div class="container mx-auto flex">

            <div class="w-full mb-10 overflow-hidden shadow-md wow fadeIn">
                <form method="POST" class="w-full h-full">
                    {% csrf_token %}
                    <div class="w-full flex items-center justify-between bg-gray-600 h-12 text-white px-5">
                        <h3 class="font-semibold text-lg">{% trans '注文番号' %}: {{ order.order_code }}</h3>
                        <span class="">{% trans '注文日時' %}: {{ order.order_date|date:'Y-m-d H:i:s' }}</span>
                    </div>
                    <div class="flex flex-no-wrap py-10 px-5">
                        <div class="w-3/4 flex flex-col justify-around">
                            <div>{% trans '合計金額' %}: &yen; {{ order.amount | intcomma }}</div>
                            <div>{% trans '注文者' %}: {{ order.last_name_orderer }} {{ order.first_name_orderer }}</div>
                            <div>{% trans 'お届け先' %}: {{ order.get_prefecture_recipient_display }}
                                {{ order.address_city_recipient }}
                                {{ order.address_detail_recipient }}</div>
                            <div>{% trans '数量' %}: {{ order.count_items_all }}</div>
                            <div>{% trans 'お支払い方法' %}: {{ order.get_payment_display }}</div>
                            <div>{% trans '処理状況' %}: {{ order.step }}</div>
                        </div>
                    </div>
                    {% for order_item in order.order_items.all %}
                    <div class="flex flex-no-wrap py-10 px-5">
                        <div style="background-image: url('{{ order_item.front.url }}');"
                            class="w-1/4 h-40 bg-cover bg-center mr-3">
                        </div>
                        <div class="w-3/4 flex flex-col justify-around">
                            <div>{% trans '商品名' %}: {{ order_item.product }}</div>
                            <div>{% trans '単価' %}: &yen; {{ order_item.price | intcomma }}</div>
                            <div>{% trans '数量' %}: {{ order_item.quantity }}</div>
                            <div>{% trans '足サイズ(左)' %}: {{ order_item.length_left }}(足長) {{ order_item.width_left }}(足幅)
                            </div>
                            <div>{% trans '足サイズ(右)' %}: {{ order_item.length_right }}(足長)
                                {{ order_item.width_right }}(足幅)</div>
                        </div>
                    </div>
                    {% endfor %}

                    <div class="w-full flex justify-around mb-5">
                        {% if order.step.step_code == "T01" or order.step.step_code == "T02" %}
                        <input type="hidden" name="target-order" value="{{ order.pk }}">
                        <button class="btn-danger text-white w-1/3 p-3">{% trans '注文取消' %}</button>
                        {% endif %}
                        {% if order.step.step_code == "T01" %}
                        <a href="{% url 'orders:bill' order.order_code %}" target="_blank"
                            class="btn text-white w-1/3 p-3">{% trans '請求書発行' %}</a>
                        {% endif %}
                        {% if order.step.step_code != "T01" and order.step.step_code != "T02" and order.step.step_code != "T99" %}
                        <a href="{% url 'orders:receipt' order.order_code %}" target="_blank"
                            class="btn text-white w-1/3 p-3">{% trans '領収書発行' %}</a>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
{% endblock %}