config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("products/", include("products.urls", namespace="products")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("designs/", include("designs.urls", namespace="designs")),
    path("feet/", include("feet.urls", namespace="feet")),
    path("carts/", include("carts.urls", namespace="carts")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("chats/", include("chats.urls", namespace="chats")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from products import views as product_views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signup/check/", views.SignUpCheckView.as_view(), name="signup-check"),
    path("signup/success/", views.SignupSuccessView.as_view(), name="signup-success"),
    path("password_reset/", views.PasswordResetView.as_view(), name="password-reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password-reset-complete",
    ),
    path(
        "mypage/update-profile/",
        views.UpdateProfileView.as_view(),
        name="update-profile",
    ),
    path(
        "mypage/change-password/",
        views.PasswordChangeView.as_view(),
        name="change-password",
    ),
    path("mypage/orders/", views.OrdersListView.as_view(), name="orders",),
    path(
        "mypage/orders/detail/<int:order_pk>/",
        views.OrdersDetailView.as_view(),
        name="orders-detail",
    ),
    path("mypage/cards/", views.CardsListView.as_view(), name="cards",),
    path("mypage/cards/add/", views.CardsAddView.as_view(), name="add-card",),
    path("mypage/mydesigns/", views.MyDesignsListView.as_view(), name="mydesigns",),
    path(
        "mypage/mydesigns/select-product/",
        views.SelectProductToCustomizeView.as_view(),
        name="select-product",
    ),
    path(
        "mypage/mydesigns/customize/<int:pk>/",
        views.MemberCustomizeView.as_view(),
        name="customize",
    ),
    path(
        "mypage/mydesigns/modify/",
        views.MemberCustomizeModifyView.as_view(),
        name="modify",
    ),
    path("mypage/footsizes/", views.FootSizeView.as_view(), name="footsizes",),
    path("mypage/footsizes/measure/", views.footsizes_measure, name="measure"),
    path(
        "mypage/footsizes/measure/rotation/",
        views.FootImageRotationView.as_view(),
        name="rotation",
    ),
    path(
        "mypage/footsizes/measure/cropper/left/",
        views.LeftFootsizePerspeciveCropperView.as_view(),
        name="crop-left",
    ),
    path(
        "mypage/footsizes/measure/cropper/right/",
        views.RightFootsizePerspeciveCropperView.as_view(),
        name="crop-right",
    ),
    path(
        "mypage/footsizes/measure/analyze/<int:pk>/",
        views.footsizes_analysis,
        name="analyze",
    ),
    path("mypage/withdrawal/", views.WithdrawalView.as_view(), name="withdrawal",),
    path(
        "mypage/withdrawal/check/",
        views.WithdrawalCheckView.as_view(),
        name="withdrawal-check",
    ),
    path(
        "withdrawal/done/", views.WithdrawalDoneView.as_view(), name="withdrawal-done",
    ),
    path("apply/", views.get_palette, name="apply"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.base import ContentFile
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, reverse, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import translation
from django.utils.html import strip_tags
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    View,
    FormView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
    TemplateView,
)
from cards import models as card_models
from carts import models as cart_models
from designs import forms as design_forms
from designs import models as design_models
from feet import models as feet_models
from feet import forms as feet_forms
from feet import analyze
from orders import models as order_models
from products import models as product_models
from . import forms, models, mixins
import stripe, base64, json


stripe.api_key = settings.STRIPE_SECRET_KEY

# インコードした画像データを画像にデコードする関数
def base64_file(data, name=None):
    _format, _img_str = data.split(";base64,")
    _name, ext = _format.split("/")
    if not name:
        name = _name.split(":")[-1]
    result = ContentFile(base64.b64decode(_img_str), name="{}.{}".format(name, ext))
    return result


class LoginView(mixins.LoggedOutOnlyView, FormView):

    """ ログイン """

    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, email=email, password=password)
        if user is not None:
            login(self.request, user)
            session_key = self.request.session.session_key
            cart_models.Cart.objects.filter(session_key=session_key).update(
                user_id=self.request.user.pk
            )
            messages.success(self.request, _("ログインしました。"))
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def log_out(request):

    """ ログアウト """

    messages.info(request, _("ログアウトしました。"))
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(mixins.LoggedOutOnlyView, FormView):

    """ 会員登録 """

    template_name = "users/signup.html"
    form_class = forms.SignUpForm

    def get_initial(self):
        if self.request.session.get("data"):
            return self.request.session["data"]
        else:
            return self.initial.copy()

    def form_valid(self, user):
        data = {
            "email": user.cleaned_data.get("email"),
            "password": user.cleaned_data.get("password"),
            "last_name": user.cleaned_data.get("last_name"),
            "first_name": user.cleaned_data.get("first_name"),
            "last_name_kana": user.cleaned_data.get("last_name_kana"),
            "first_name_kana": user.cleaned_data.get("first_name_kana"),
            "gender": user.cleaned_data.get("gender"),
        }
        self.request.session["data"] = data
        return redirect(reverse("users:signup-check"))


class SignUpCheckView(mixins.LoggedOutOnlyView, FormView):

    """ 会員登録情報確認 """

    template_name = "users/signup-check.html"

    def get(self, request):
        data = request.session.get("data")
        return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        data = request.session.get("data")
        user = models.User.objects.create(
            email=data["email"],
            last_name=data["last_name"],
            first_name=data["first_name"],
            last_name_kana=data["last_name_kana"],
            first_name_kana=data["first_name_kana"],
            gender=data["gender"],
        )
        user.set_password(data["password"])
        user.save()
        email = data["email"]
        html_message = render_to_string("emails/registration-done.html")
        send_mail(
            _("Uniwalk 会員登録ありがとうございます。"),
            strip_tags(html_message),
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
            html_message=html_message,
        )
        del request.session["data"]
        return redirect(reverse("users:signup-success"))


class SignupSuccessView(mixins.LoggedOutOnlyView, View):

    """ 会員登録完了 """

    def get(self, request):
        return render(request, "users/signup-success.html")


class PasswordResetView(PasswordResetView):

    """ パスワード再設定申し込み """

    form_class = forms.PasswordResetForm
    template_name = "users/password-reset.html"
    subject_template_name = "emails/password-reset-subject.txt"
    email_template_name = "emails/password_reset_form.html"
    html_email_template_name = "emails/password_reset_form.html"
    success_url = reverse_lazy("users:password-reset-done")


class PasswordResetDoneView(PasswordResetDoneView):

    """ パスワード再設定申し込み完了 """

    template_name = "users/password-reset-done.html"


class PasswordResetConfirmView(PasswordResetConfirmView):

    """ パスワード再設定 """

    form_class = forms.SetPasswordForm
    template_name = "users/password-reset-confirm.html"
    success_url = reverse_lazy("users:password-reset-complete")

    def form_valid(self, form):
        email = self.user.email
        html_message = render_to_string("emails/password-reset-done.html")
        send_mail(
            _("Uniwalk パスワード再設定完了のお知らせ"),
            strip_tags(html_message),
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
            html_message=html_message,
        )
        return super().form_valid(form)


class PasswordResetCompleteView(PasswordResetCompleteView):

    """ パスワード再設定完了 """

    template_name = "users/password-reset-complete.html"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    """ 会員登録情報変更 """

    form_class = forms.UpdateProfileForm
    template_name = "users/update-profile.html"
    success_message = _("会員情報を変更しました。")

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("users:update-profile")

    def form_valid(self, form):
        user = form.save()
        user.save()
        email = form.cleaned_data.get("email")
        html_message = render_to_string("emails/profile-change-done.html")
        send_mail(
            _("Uniwalk 会員情報変更のお知らせ"),
            strip_tags(html_message),
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
            html_message=html_message,
        )
        return super().form_valid(form)


class PasswordChangeView(mixins.LoggedInOnlyView, PasswordChangeView):

    """ パスワード変更 """

    form_class = forms.PasswordChangeForm
    template_name = "users/password-change.html"

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.save()
        email = self.request.user.email
        html_message = render_to_string("emails/password-change-done.html")
        send_mail(
            _("UniWalk パスワード変更のお知らせ"),
            strip_tags(html_message),
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
            html_message=html_message,
        )
        update_session_auth_hash(self.request, form.user)
        messages.success(self.request, _("パスワードを変更しました。"))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("users:update-profile")


class OrdersListView(mixins.LoggedInOnlyView, ListView):

    """ 注文履歴 """

    model = order_models.Order
    template_name = "orders/order-list.html"
    context_object_name = "orders"
    paginate_by = 5

    def get_queryset(self):
        try:
            return order_models.Order.objects.filter(
                user_id=self.request.user.pk
            ).order_by("-order_date")
        except order_models.Order.DoesNotExist:
            return None

    def post(self, *args, **kwargs):
        order_pk = self.request.POST.get("target-order")
        target = order_models.Order.objects.filter(pk=order_pk)
        cancel = order_models.Step.objects.get(step_code="T99")
        target.update(step=cancel)
        email = self.request.user.email
        html_message = render_to_string(
            "emails/cancel-done.html",
            {"order_code": order_models.Order.objects.get(pk=order_pk).order_code},
        )
        send_mail(
            _("Uniwalk ご注文取消しのご連絡"),
            strip_tags(html_message),
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
            html_message=html_message,
        )
        messages.success(self.request, _("注文を取消しました。"))
        return redirect("users:orders")


class OrdersDetailView(mixins.LoggedInOnlyView, DetailView):

    """ 注文詳細 """

    model = order_models.Order
    template_name = "orders/order-detail.html"
    context_object_name = "order"
    pk_url_kwarg = "order_pk"

    def get(self, request, *args, **kwargs):
        try:
            return super(OrdersDetailView, self).get(request, *args, **kwargs)
        except ObjectDoesNotExist:

templates/users/login.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans 'ログイン' %}
{% endblock page_title%}

{% block content %}
<div class="flex items-center min-h-75vh rounded-xl py-16"
  style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
  <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
    <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
      <i class="fas fa-lock fa-3x text-white wow fadeIn"></i>
    </div>
    <div class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">
      {% trans 'ログイン' %}
    </div>

    {% trans "ログイン" as login %}
    {% include 'mixins/auth/form_auth.html' with form=form cta=login %}

    <div class="mt-5 wow fadeIn">
      <span class="mr-2">{% trans "パスワードを忘れた方は" %}</span>
      <a href="{% url 'users:password-reset' %}" class="btn-link">{% trans 'パスワード再発行' %}</a>
    </div>

    <div class="mt-5 wow fadeIn">
      <span class="mr-2">{% trans 'アカウントをお持ちでない方は' %}</span>
      <a href="{% url 'users:signup' %}" class="btn-link">
        {% trans '会員登録' %}
      </a>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
{% endblock %}

templates/users/password-change.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans 'パスワード再設定' %}
{% endblock page_title%}

{% block content %}
<div class="mx-auto min-h-75vh px-10 py-10 rounded-xl"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container mx-auto">
        <div class="w-full shadow-lg">
            {% include 'partials/mypage-menu.html' %}
        </div>

        <div class="w-full flex flex-col mb-10">
            <div
                class="container bg-white w-2/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 mt-24 relative">
                <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute"
                    style="top: -3rem;">
                    <i class="fas fa-redo-alt fa-3x text-white wow fadeIn"></i>
                </div>
                <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">{% trans 'パスワード変更' %}</h2>
                <div class="w-1/2 mx-auto">
                    {% trans "変更する" as set %}
                    {% include 'mixins/auth/form_auth.html' with form=form cta=set %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

{% block javascript %}
{% endblock %}

templates/users/password-reset-complete.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans "パスワード再設定完了" %}
{% endblock page_title %}

{% block content %}

<div class="flex items-center min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-check fa-3x text-white wow fadeIn"></i>
        </div>
        <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">{% trans "パスワード再設定完了" %}</h2>
        <h3 class="font-medium text-2xl mb-3 wow fadeIn">{% trans "パスワード再設定が完了しました。" %}</h3>
        <p class="text-center mb-5 wow fadeIn">
            {% trans "下のボタンを押すとログインページに移動します。" %}
        </p>
        <a href="{% url 'users:login' %}" class="btn bg-blue-500 text-white wow fadeIn">{% trans 'ログインへ' %}</a>
    </div>
</div>

{% endblock content %}

{% block javascript %}

{% endblock %}

templates/users/password-reset-confirm.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans 'パスワード再設定' %}
{% endblock page_title%}

{% block content %}
<div class="flex items-center min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        {% if validlink %}
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-redo-alt fa-3x text-white wow fadeIn"></i>
        </div>
        <div class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">
            {% trans 'パスワード再設定' %}
        </div>
        <h3 class="font-medium text-xl mb-3 wow fadeIn">{% trans "新しいパスワードを設定してください。" %}</h3>

        {% trans "設定する" as set %}
        {% include 'mixins/auth/form_auth.html' with form=form cta=set %}

        {% else %}
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-times fa-3x text-white wow fadeIn"></i>
        </div>
        <div class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">
            {% trans 'エラー' %}
        </div>
        <p class="wow fadeIn">
            {% trans "パスワード再設定用リンクが無効です。新たにパスワード再設定を申し込んでください。" %}
        </p>

        {% endif %}
    </div>
</div>
{% endblock content %}

{% block javascript %}
{% endblock %}

templates/users/password-reset-done.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans "パスワード再設定申込み完了" %}
{% endblock page_title %}

{% block content %}
<div class="flex items-center min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="far fa-envelope fa-3x text-white wow fadeIn"></i>
        </div>
        <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">{% trans "パスワード再発行申込み完了" %}</h2>
        <h3 class="font-medium text-2xl mb-3 wow fadeIn">{% trans "ご登録のメールアドレス宛にパスワード再発行用メールを送信いたしました。" %}</h3>
        <p class="text-center mb-5 wow fadeIn">
            {% trans "メールの内容をご確認いただきますよう、お願いいたします。" %}<br>{% trans "※メールが届かない場合はメールアドレスをご確認の上、再度お試しください。" %}</p>
    </div>
</div>

{% endblock content %}

{% block javascript %}

{% endblock %}

templates/users/password-reset.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans 'パスワード再設定申込み' %}
{% endblock page_title%}

{% block content %}
<div class="flex items-center min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-redo-alt fa-3x text-white wow fadeIn"></i>
        </div>
        <div class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">
            {% trans 'パスワード再設定申込み' %}
        </div>

        {% trans "申し込む" as reset %}
        {% include 'mixins/auth/form_auth.html' with form=form cta=reset %}

        <div class="mt-5 wow fadeIn">
            <span class="mr-2">{% trans 'パスワードを思い出した方は' %}</span>
            <a href="{% url 'users:login' %}" class="btn-link">
                {% trans 'ログイン' %}
            </a>
        </div>
    </div>
    {% endblock content %}

    {% block javascript %}
    {% endblock %}

templates/users/signup-success.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans "会員登録完了" %}
{% endblock page_title %}

{% block content %}
<div class="flex items-center min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-check fa-3x text-white wow fadeIn"></i>
        </div>
        <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">{% trans "会員登録完了" %}</h2>
        <h3 class="font-medium text-xl mb-3 wow fadeIn">{% trans "本登録が完了いたしました。" %}</h3>
        <p class="text-center mb-5 wow fadeIn">
            {% trans "それではショッピングをお楽しみください。" %}<br>
            {% trans "お届け住所や連絡先などの詳細情報は、「マイアカウント」で登録できます。" %}<br>
            {% trans "今後ともご愛顧賜りますようよろしくお願い申し上げます。" %}
        </p>
        <a href="{% url 'users:login' %}" class="btn mt-5 wow fadeIn">
            {% trans "ログイン" %}
        </a>

    </div>
</div>
{% endblock content %}

{% block javascript %}

{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans "会員登録" %}
{% endblock page_title %}

{% block content %}
<div class="flex items-center min-h-75vh rounded-xl py-16"
  style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
  <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
    <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
      <i class="fas fa-user-plus fa-3x text-white wow fadeIn"></i>
    </div>
    <div class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">
      {% trans '会員登録' %}
    </div>

    {% trans "会員登録" as registration %}
    {% include 'mixins/auth/form_auth.html' with form=form cta=registration %}

    <div class="mt-5 text-center wow fadeIn">
      <span class="mr-2">{% trans "既にアカウントを持っていますか?" %}</span>
      <a href="{% url 'users:login' %}" class="btn-link">
        {% trans "ログイン" %}
      </a>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
{% endblock %}

templates/users/update-profile.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans '会員情報変更' %}
{% endblock page_title%}

{% block content %}
<div class="mx-auto px-10 py-10 rounded-xl"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container mx-auto">
        <div class="w-full shadow-lg">
            {% include 'partials/mypage-menu.html' %}
        </div>

        <div class="w-full flex flex-col mb-10">
            <div
                class="container min-h-75vh bg-white w-2/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 mt-24 relative">
                <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute"
                    style="top: -3rem;">
                    <i class="fas fa-user-cog fa-3x text-white wow fadeIn"></i>
                </div>
                <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">{% trans '会員情報変更' %}</h2>

                <div class="flex w-full justify-between items-center mb-5 border border-b p-5">
                    <span>{% trans 'パスワード変更の場合は、右のボタンを押してください。' %}</span>
                    <a href="{% url 'users:change-password' %}" class="w-1/3 btn-warning">{% trans 'パスワード変更' %}</a>
                </div>

                <form method="POST" enctype="multipart/form-data" class="w-full p-5">
                    <div class="wow fadeIn">
                        {% csrf_token %}

                        {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <span class="text-red-700 font-medium text-sm">{{ error }}</span>
                        {% endfor %}
                        {% endif %}

                        {% for field in form %}
                        {% include 'mixins/auth/form_input.html' with field=field %}
                        {% endfor %}
                    </div>
                    <button class="btn bg-blue-500 text-white mt-5">{% trans '変更する' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<link href="{% static 'css/datepicker.css' %}" rel="stylesheet">
<script src="{% static 'js/datepicker.min.js' %}"></script>
<script src="{% static 'js/i18n/datepicker.ja-JP.js' %}"></script>
<script>
    // 日付設定用カレンダーウィジェットを呼び出す
    $(function () {
        $(".datepicker").datepicker({
            format: 'yyyy-mm-dd',
            language: 'ja-JP',
        });
    });
</script>
{% endblock %}

templates/users/withdrawal-done.html
{% extends "base.html" %}
{% load i18n static %}

{% block page_title %}
{% trans "会員脱退完了" %}
{% endblock page_title %}

{% block content %}
<div class="flex items-center min-h-75vh rounded-xl py-16"
    style="background-image: url({% static 'images/pattern.svg' %}); background-repeat: repeat;">
    <div class="container bg-white w-1/3 rounded-xl h-full mx-auto my-10 flex flex-col items-center p-12 relative">
        <div class="flex items-center justify-center bg-indigo-600 w-24 h-24 rounded-full absolute" style="top: -3rem;">
            <i class="fas fa-user-slash fa-3x text-white wow fadeIn"></i>
        </div>
        <h2 class="text-indigo-800 mt-3 mb-5 text-3xl font-semibold">{% trans "会員脱退完了" %}</h2>
        <h3 class="font-medium text-2xl mb-3 wow fadeIn">{% trans "会員脱退が完了しました。" %}</h3>
        <p class="text-center mb-5 wow fadeIn">{% trans "またのご利用お待ちしております！" %}</p>
        <a href="{% url 'core:home' %}" class="btn mt-5">
            {% trans "トップへ" %}
        </a>
    </div>
</div>
{% endblock content %}

{% block javascript %}
{% endblock %}